name: kukhurikaa
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.69.2
  flutter_slidable: ^3.1.2
  skeletonizer: ^1.4.2
  adaptive_theme: ^3.6.0
  google_nav_bar: ^5.0.7
  dashed_circular_progress_bar: ^0.0.6
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
